Array Methods

In [ ]:
import numpy as np

print(np.zeros((3,4)))
print()
print(np.ones(shape=(3,4)))
print()
print(np.identity(4))
print()
print(np.full(fill_value=6,shape=(3,4)))
print()
print(np.eye(5,3))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [29]:
print(np.arange(start=1,stop=5,step=1))

np.arange(stop=5)

[1 2 3 4]


array([0, 1, 2, 3, 4])

In [33]:
np.linspace(start=1,stop=5,num=10,retstep=True)


(array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
        3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ]),
 np.float64(0.4444444444444444))

In [9]:
import numpy as np
a = np.arange(1,6)
print(a)
print(a.max())
print(a.min())
print(a.sum())
print(a.mean())
print(np.median(a,overwrite_input=True))
print(np.std(a))

[1 2 3 4 5]
5
1
15
3.0
3.0
[1 2 3 4 5]
1.4142135623730951


In [17]:
a2 = np.array([5,2,1,3,5,6])
print(np.median(a2,overwrite_input=True))
print(a2)
print(np.percentile(a2,q=0)) # before 1 0% of eles are present
print(np.percentile(a2,q=25)) # before 2.25 25% of eles are present
print(np.percentile(a2,q=50)) # before 4 50% of eles are present
print(np.percentile(a2,q=75)) # before 5 75% of eles are present
print(np.percentile(a2,q=100)) # before 6 100% of eles are present


4.0
[1 2 3 5 5 6]
1.0
2.25
4.0
5.0
6.0


In [20]:
a3 = [4,3,2,5,1]
print(np.var(a))
print(np.std(a))

2.0
1.4142135623730951


In [ ]:
import numpy.random as r

print(r.rand(3))
arr = r.rand(3,2)
print(arr)


[0.5488135  0.71518937 0.60276338]
[[0.54488318 0.4236548 ]
 [0.64589411 0.43758721]
 [0.891773   0.96366276]]
1.0965636704059414
1.0834390922249528


In [ ]:
b = r.randn(3)
print(np.mean(b))
print(np.std(b))

-0.06540857679725225
0.8713816082685264


In [438]:
c = r.randint(1,10)
print(r.randint(50,100))
print(r.randint(50,100,(20,)))
print(r.randint(50,100,(5,4)))
print(r.choice(['red','blue','green','black'],2,replace=False))
print(r.choice(['red','blue','green','black'],2,p = [0,0.5,0,0.5]))

73
[93 74 70 85 96 82 84 92 78 87 86 68 92 85 89 85 51 79 70 87]
[[85 96 84 77]
 [99 64 92 80]
 [77 54 54 56]
 [91 91 53 89]
 [94 86 77 63]]
['blue' 'green']
['blue' 'black']


In [ ]:
import numpy as np
b1 = np.array([5,2,3,6,7])
print(np.where(b1>5,'yes','no')) 
print((b1>4).all())
print((b1>4).any())

['no' 'no' 'no' 'yes' 'yes']
False
True


In [4]:
sq_rt_arr = np.array([4,9,16,25,])
print(np.sqrt(sq_rt_arr))

[2. 3. 4. 5.]


In [7]:
a5 = np.array([0,1,2])
a6 = np.exp(a5)
print(a6)
print(np.log(a6))

[1.         2.71828183 7.3890561 ]
[0. 1. 2.]


In [14]:
a7 = np.arange(1,11)
a7.shape
print(a7.reshape(5,2))
print(a7.reshape(2,5))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [65]:
import numpy.random as r
arr2 = r.randint(1,100,12)

print(arr2)
r.seed(0)
print(np.reshape(arr2,(2,3,1,2)))

[45 48 65 68 68 10 84 22 37 88 71 89]
[[[[45 48]]

  [[65 68]]

  [[68 10]]]


 [[[84 22]]

  [[37 88]]

  [[71 89]]]]


In [ ]:
arr3 = np.array([[10,20,30],[40,50,60]])
# print(arr3.reshape(-1))
print(np.ravel(arr3))
# ravel will always return 1D array



[10 20 30 40 50 60]


In [71]:
arr4 = np.array([[10,20,30,40],[50,60,70,80]])
print(np.reshape(arr4,(2,2,2)))

[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]
