In [1]:
import numpy as np

a1 = np.array([10,21.2,],dtype='str',ndmin=2)
a2 = np.array(a1,copy=False)
a1[0][0] = 13
print(a1,a2)

[['13' '21.2']] [['13' '21.2']]


In [2]:
print({'a':1,'b':2}.values())

dict_values([1, 2])


In [5]:
import numpy as np
a_zero = np.array(10)
a_one = np.array([10,20,30])
a_two = np.array([[10.,20],[30,40]])
print(f'dimensions of {a_zero} is {a_zero.ndim} and size is {a_zero.size} and datatype is {a_zero.dtype} and shape is {a_zero.shape}')
print(f'dimesions of {a_one} are {a_one.ndim} and size is {a_one.size} and datatype is {a_one.dtype} and shape is {a_one.shape}')
print(f'dimensions of {a_two} are {a_two.ndim} and size is {a_two.size} and datatype is {a_two.dtype} and shape is {a_two.shape}')

dimensions of 10 is 0 and size is 1 and datatype is int64 and shape is ()
dimesions of [10 20 30] are 1 and size is 3 and datatype is int64 and shape is (3,)
dimensions of [[10. 20.]
 [30. 40.]] are 2 and size is 4 and datatype is float64 and shape is (2, 2)


Indexing and slicing

In [ ]:
import numpy as np
#1-D array
a1 = np.array([10,20,30,40,50])
print(a1[0],a1[-1])
print(a1[2:])
print(a1[:-5:-1])

10 50
[30 40 50]
[50 40 30 20]


In [ ]:
#2-D array
import numpy as np
a2 = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(a2[1])
print()
print(a2[2][0:])
print()
print(a2[-1][-1:0:-1])
print()
print(a2[::-1,::-1])
print()
print(a2[::2,::2])
print()
print(a2[:2:,1:])
print()
print(a2[-1::-2,-1:0:-1])
print()
print(a2[2,:0:-1])

[40 50 60]

[70 80 90]

[90 80]

[[90 80 70]
 [60 50 40]
 [30 20 10]]

[[10 30]
 [70 90]]

[[20 30]
 [50 60]]

[[90 80]
 [30 20]]

[90 80]


In [ ]:
import numpy as np
a3 = np.array(
    [
        [
            [10,20,30],[40,50,60],[70,80,90]
        ],
        [
            [15,25,35],[45,55,65],[75,85,95]
        ]
    ]
    )
print(a3)
print()
print(a3[0,1,1])
print()
print(a3[0:,0:,1])
print()
print(a3[::-1,::-1,-1::-2])
print()
print(a3[:,0])
print()
print(a3[:1:,::2,::-2])
print()
print(a3[:,:,1])

[[[10 20 30]
  [40 50 60]
  [70 80 90]]

 [[15 25 35]
  [45 55 65]
  [75 85 95]]]

50

[[20 50 80]
 [25 55 85]]

[[[95 75]
  [65 45]
  [35 15]]

 [[90 70]
  [60 40]
  [30 10]]]

[[10 20 30]
 [15 25 35]]

[[[30 10]
  [90 70]]]

[[20 50 80]
 [25 55 85]]


In [ ]:
import numpy as np
arr1 = np.array([1,2,3,5])
arr2 = np.array([5,5,5,5])
print(arr1+arr2)
print()
print(arr1-arr2)
print()
print(arr1*arr2)
print()
print(arr1/arr2)
print()
print(arr1//arr2)
print()
print(arr1%arr2)
print()
print(arr1**arr2)
print()
print(arr1>arr2)
print()
print(arr1>=arr2)
print()
print(arr1<arr2)
print()
print(arr1<=arr2)
print()
print(arr1==arr2)
print()
print(arr1!=arr2)
print()
print(arr1^arr2)
print()
print(arr1>>arr2)
print()
print(arr1<<arr2)
print()
print(arr1|arr2)
print()
print(arr1&arr2)
print()

[ 6  7  8 10]

[-4 -3 -2  0]

[ 5 10 15 25]

[0.2 0.4 0.6 1. ]

[0 0 0 1]

[1 2 3 0]

[   1   32  243 3125]

[False False False False]

[False False False  True]

[ True  True  True False]

[ True  True  True  True]

[False False False  True]

[ True  True  True False]

[4 7 6 0]

[0 0 0 0]

[ 32  64  96 160]

[5 7 7 5]

[1 0 1 5]



In [ ]:
b = arr1 == arr2
arr2[~ b]

array([5, 5, 5])

In [ ]:
c = 3
print(arr1+c)

[4 5 6 8]
